pipeline:
  name: ShellPipeline
  identifier: ShellPipeline
  projectIdentifier: Do_Not_Delete_Prakhar
  orgIdentifier: Ng_Pipelines_K8s_Organisations
  tags: {}
  stages:
    - stage:
        name: shell
        identifier: shell
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 12
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
