pipeline:
  name: testMyPipeline2
  identifier: testMyPipeline2
  projectIdentifier: demoPrakhar
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: asdfv
        identifier: asdfv
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo Ib
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
