name: relicx-ai
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-22.04

    steps:
      - run: $ easy_install six
      - name: relicx-ai-test
        uses: relicx-ai/relicx-githubaction@v1.4
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          app_id: '1c4b44c5-3576-47d1-90bd-f07a1f293143'
          command: 'run_test_suite'
          test_suite_id: '28ddd0f1-6216-4520-a094-54786b1f2c91'
          environment_id: '1fcd613a-0238-4a3d-98a9-262c925cfac2'
          wait: false


